apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-nginx-ingress
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/instance: ingress-nginx
data:
  hsts: "false"
  ssl-redirect: "false"
  server-tokens: "false"
  proxy-body-size: "50m"
